(defun fix-blog-title ()
  (interactive)
  (beginning-of-buffer)
  (re-search-forward "title")
  (beginning-of-line)
  (insert "#+")
  (replace-string-in-region "\'" "" (line-beginning-position) (line-end-position))
  )


(defun fix-blog-date ()
  (interactive)
  (beginning-of-buffer)
  (re-search-forward "date")
  (beginning-of-line)
  (insert "#+")
  (re-search-forward ": ")
  (kill-visual-line)
  (insert (format-time-string "<%Y-%m-%d>" (date-to-time (current-kill 0 t))))
  )

(defun delete-draft-line ()
  (interactive)
  (beginning-of-buffer)
  (re-search-forward "draft:")
  (beginning-of-line)
  (kill-visual-line)
  (kill-visual-line)
  )

(defun fix-blog-tags ()
  (interactive)
  (beginning-of-buffer)
  (re-search-forward "^tags:")
  (beginning-of-line)
  (insert "#+file")
  (replace-string-in-region "\'" "" (line-beginning-position) (line-end-position))
  (replace-string-in-region "," "" (line-beginning-position) (line-end-position))
  (replace-string-in-region "[" "" (line-beginning-position) (line-end-position))
  (replace-string-in-region "]" "" (line-beginning-position) (line-end-position))
  (downcase-region (line-beginning-position) (line-end-position))
  )

(defun delete-markdown-header-lines ()
  (interactive)
  (beginning-of-buffer)
  (re-search-forward "^---$")
  (beginning-of-line)
  (kill-visual-line)
  (kill-visual-line)
  (re-search-forward "^---$")
  (beginning-of-line)
  (kill-visual-line)
  )

(defun convert-markdown-eol ()
  (interactive)
  (beginning-of-line)
  (while (re-search-forward "[[:blank:]]+$" nil t)
	(replace-match "\\\\\\\\")))

(defun convert-markdown-header ()
  (interactive)
  (progn
    (delete-markdown-header-lines)
   (fix-blog-title)
   (fix-blog-date)
   (delete-draft-line)
   (fix-blog-tags)
   (convert-markdown-eol)
   ))
