(point)

(defun oremus-open-eww ()
  (interactive)
  (setq oremus-passage (read-string "Passage: "))
  (setq oremus-passage (s-replace " " "%20" oremus-passage))
  (setq oremus-link (concat "https://bible.oremus.org/?version=NRSV&passage=" oremus-passage "&vnum=NO&fnote=NO&omithidden=YES"))
  (eww-browse-url oremus-link))

(defun oremus-cleanup ()
  (interactive)
  (beginning-of-buffer)
  (while (re-search-forward "" nil t)
    (replace-match "\""))
  (beginning-of-buffer)
  (while (re-search-forward "" nil t)
    (replace-match "\""))
  (beginning-of-buffer)
  (while (re-search-forward "" nil t)
    (replace-match "\'"))
  (beginning-of-buffer)
  (while (re-search-forward "" nil t)
    (replace-match "\'"))
  (beginning-of-buffer)
  (while (re-search-forward "" nil t)
    (replace-match "\'"))
  (beginning-of-buffer)
  (while (re-search-forward "" nil t)
    (replace-match "—"))
  )


(defun oremus-get-html ()
  (interactive)
  (setq oremus-passage (read-string "Passage: "))
  (setq oremus-passage (s-replace " " "%20" oremus-passage))
  (setq oremus-link (concat "https://bible.oremus.org/?version=NRSV&passage=" oremus-passage "&vnum=NO&fnote=NO&omithidden=YES"))
  (switch-to-buffer (url-retrieve-synchronously oremus-link)))

(defun oremus-clean-html ()
  (interactive)
  (beginning-of-buffer)
  (search-forward "passageref\">")
  (kill-region (point) 1)
  (search-forward "</div><!-- class=\"bibletext\" -->")
  (beginning-of-line)
  (kill-region (point) (point-max))
  (beginning-of-buffer)
  (while (re-search-forward "<p>" nil t)
    (replace-match "\n"))
  (beginning-of-buffer)
  (while (re-search-forward "<!.+?->" nil t)
    (replace-match ""))
  (beginning-of-buffer)
  (while (re-search-forward "<.+?>" nil t)
    (replace-match ""))
  (beginning-of-buffer)
  (while (re-search-forward "&nbsp;" nil t)
    (replace-match " "))
  (beginning-of-buffer)
  (while (re-search-forward "&#147;" nil t)
    (replace-match "\""))
  (beginning-of-buffer)
  (while (re-search-forward "&#148;" nil t)
    (replace-match "\""))
  (beginning-of-buffer)
  (while (re-search-forward "&#145;" nil t)
    (replace-match "\'"))
  (beginning-of-buffer)
  (while (re-search-forward "&#146;" nil t)
    (replace-match "\'"))
  (beginning-of-buffer)
  (while (re-search-forward "&#151;" nil t)
    (replace-match "—"))
  (delete-extra-blank-lines)
  (clipboard-kill-ring-save (point-min) (point-max))
  (kill-buffer)
  )



(defun oremus-get-passage ()
  (interactive)
  (setq oremus-passage (read-string "Passage: "))
  (setq oremus-passage (s-replace " " "%20" oremus-passage))
  (setq oremus-link (concat "https://bible.oremus.org/?version=NRSV&passage=" oremus-passage "&vnum=NO&fnote=NO&omithidden=YES"))
  (switch-to-buffer (url-retrieve-synchronously oremus-link))
  (beginning-of-buffer)
  (search-forward "passageref\">")
  (kill-region (point) 1)
  (search-forward "</div><!-- class=\"bibletext\" -->")
  (beginning-of-line)
  (kill-region (point) (point-max))
  (beginning-of-buffer)
  (while (re-search-forward "<p>" nil t)
    (replace-match "\n"))
  (beginning-of-buffer)
  (while (re-search-forward "<!.+?->" nil t)
    (replace-match ""))
  (beginning-of-buffer)
  (while (re-search-forward "<.+?>" nil t)
    (replace-match ""))
  (beginning-of-buffer)
  (while (re-search-forward "&nbsp;" nil t)
    (replace-match " "))
  (beginning-of-buffer)
  (while (re-search-forward "&#147;" nil t)
    (replace-match "\""))
  (beginning-of-buffer)
  (while (re-search-forward "&#148;" nil t)
    (replace-match "\""))
  (beginning-of-buffer)
  (while (re-search-forward "&#145;" nil t)
    (replace-match "\'"))
  (beginning-of-buffer)
  (while (re-search-forward "&#146;" nil t)
    (replace-match "\'"))
  (beginning-of-buffer)
  (while (re-search-forward "&#151;" nil t)
    (replace-match "—"))
  (delete-extra-blank-lines)
  (clipboard-kill-ring-save (point-min) (point-max))
  (kill-buffer)
  (yank))


(defun oremus-get-html ()
  (interactive)
  (setq oremus-passage (read-string "Passage: "))
  (setq oremus-passage (s-replace " " "%20" oremus-passage))
  (setq oremus-link (concat "https://bible.oremus.org/?version=NRSV&passage=" oremus-passage "&vnum=NO&fnote=NO&omithidden=YES"))
  (switch-to-buffer (url-retrieve-synchronously oremus-link)))
